---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-hw-deployment
  namespace: apps
  labels:
    app: webflux-hw-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webflux-hw-pod
  template:
    metadata:
      labels:
        app: webflux-hw-pod
    spec:
      containers:
      - name: webflux-hw-container
        image: ghcr.io/leifll/webflux-hw:main-a1ccb12
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: webflux-hw-service
  namespace: apps
spec:
  selector:
    app: webflux-hw-pod
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webflux-hw-virtualservice
  namespace: apps
spec:
  hosts:
  - "webflux-hw.leiflindback.se"
  gateways:
  - istio-system/public-gateway
  http:
  - match:
    - uri:
        prefix: /webflux-hw
    route:
    - destination:
        port:
          number: 8000
        host: webflux-hw-service.apps.svc.cluster.local
