---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-hw-deployment
  namespace: apps
  labels:
    app: webflux-hw-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webflux-hw-pod
  template:
    metadata:
      labels:
        app: webflux-hw-pod
    spec:
      containers:
      - name: webflux-hw-container
        image: ghcr.io/leifll/webflux-hw:main-a1ccb12
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: webflux-hw-service
  namespace: apps
spec:
  selector:
    app: webflux-hw-pod
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: webflux-hw-ingress
  namespace: apps
spec:
  rules:
  - http:
      paths:
      - path: /webflux-hw
        pathType: Prefix
        backend:
          service:
            name: webflux-hw-service
            port:
              number: 80
